import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from 'next/router'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import anime from 'animejs'

export default function Home() {
  const router = useRouter()
  useEffect(() => {
    const vid1 = document.getElementById('vid1')
    vid1.play();
  }, [router.isReady])

  function startGame() {
    const title = document.getElementById("title");
    const text = document.getElementById("text");
    const subtext = document.getElementById("subtext")
    anime({
      target: [text, subtext],
      opacity: 0,
    })
    axios({
      method: "get",
      url: "https://rygb.tech:8444/getTriviaQuestions"
    }).then({

    })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div id="title" className={styles.slide} style={{ backgroundColor: "black" }}>
          <video loop id="vid1" className={styles.video} >
            <source type='video/mp4' src="hard.mp4"></source>
          </video>
          <div className={styles.textContainer}>
            <h1 id="text" className={styles.text} style={{ fontSize: "50px", position: "relative" }}>Trivia Game</h1>
            <p id="subtext" className={styles.subtext} style={{ position: "relative" }}>by RYGB</p>
            <div className={styles.doublegrid}>
              <input className={styles.ename} placeholder="What's your name?"></input>
              <button className={styles.button} onClick={() => startGame()}>Play</button>
            </div>
          </div>
        </div>
        <div id="carosel">

        </div>
      </div>
    </div>
  )
}
